# Generated by Django 3.2.19 on 2023-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cover',
            old_name='texto_h1',
            new_name='text_h1',
        ),
        migrations.RenameField(
            model_name='cover',
            old_name='texto_h3',
            new_name='text_h3',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='titulo',
            new_name='title',
        ),
    ]
