# Generated by Django 3.2.19 on 2023-11-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingles', '0003_auto_20231128_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_en',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='contact_form_en',
            options={'verbose_name_plural': 'Formulario de contacto'},
        ),
        migrations.AlterModelOptions(
            name='cover_en',
            options={'verbose_name_plural': 'Cover'},
        ),
        migrations.AlterModelOptions(
            name='features_en',
            options={'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='item_features_en',
            options={'verbose_name_plural': 'Items features'},
        ),
        migrations.AlterModelOptions(
            name='lastest_post_en',
            options={'verbose_name_plural': 'Ultimos post'},
        ),
        migrations.AlterModelOptions(
            name='menu_en',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='our_work_en',
            options={'verbose_name_plural': 'Mis trabajos'},
        ),
        migrations.AlterModelOptions(
            name='owr_services_en',
            options={'verbose_name_plural': 'Mis servicios'},
        ),
        migrations.AlterModelOptions(
            name='posts_en',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='presentation_en',
            options={'verbose_name_plural': 'Presentaciones'},
        ),
        migrations.AlterModelOptions(
            name='prices_en',
            options={'verbose_name_plural': 'Precios'},
        ),
        migrations.AlterModelOptions(
            name='scoreboard_en',
            options={'verbose_name_plural': 'Scoreboard'},
        ),
        migrations.AlterModelOptions(
            name='see_more_en',
            options={'verbose_name_plural': 'Ver mas'},
        ),
        migrations.AlterModelOptions(
            name='services_en',
            options={'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='services_list_en',
            options={'verbose_name_plural': 'Lista de servicios'},
        ),
        migrations.AlterModelOptions(
            name='services_prices_en',
            options={'verbose_name_plural': 'Precios por servicios'},
        ),
        migrations.AlterModelOptions(
            name='social_links_en',
            options={'verbose_name_plural': 'Links sociales'},
        ),
        migrations.AlterModelOptions(
            name='suscribe_en',
            options={'verbose_name_plural': 'Suscripcion'},
        ),
        migrations.AlterModelOptions(
            name='team_en',
            options={'verbose_name_plural': 'Equipo'},
        ),
        migrations.AlterModelOptions(
            name='testimonials_en',
            options={'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AlterModelOptions(
            name='title_en',
            options={'verbose_name_plural': 'Título'},
        ),
        migrations.AlterModelOptions(
            name='worker_en',
            options={'verbose_name_plural': 'Trabjadores'},
        ),
    ]
