# Generated by Django 3.2.19 on 2023-11-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Espannol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Form_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name_placeholder', models.CharField(max_length=100)),
                ('email_placeholder', models.CharField(max_length=100)),
                ('message_placeholder', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Features_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='features')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Features_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('icon', models.ImageField(upload_to='features_item')),
            ],
        ),
        migrations.CreateModel(
            name='Lastest_Post_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_Work_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OWR_Services_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts')),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('comentarios', models.IntegerField()),
                ('content', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subitle', models.TextField()),
                ('video_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prices_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboard_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='scoreboard')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='See_More_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ImageField(upload_to='icono_servicio')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services_Prices_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_links_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=255)),
                ('twiter', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suscribe_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('input_placeholder', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('ocupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ocupation', models.CharField(max_length=100)),
                ('short_phrase', models.CharField(max_length=255)),
                ('long_phrase', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cover',
            new_name='Cover_ES',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_ES',
        ),
        migrations.RenameModel(
            old_name='Titulo',
            new_name='Title_ES',
        ),
        migrations.RenameField(
            model_name='cover_es',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cover_es',
            old_name='texto_h1',
            new_name='text_h1',
        ),
        migrations.RenameField(
            model_name='cover_es',
            old_name='texto_h3',
            new_name='text_h3',
        ),
        migrations.RenameField(
            model_name='title_es',
            old_name='titulo',
            new_name='title',
        ),
        migrations.CreateModel(
            name='services_list_ES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espannol.services_prices_es')),
            ],
        ),
    ]
